services:
  app:
    build: .
    volumes:
      - ./src:/var/www/html:cached
      - /var/www/html/vendor
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=taskboard
      - DB_USERNAME=taskboard
      - DB_PASSWORD=password
    depends_on:
      - db
    ports:
      - "8000:80"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: taskboard
      POSTGRES_USER: taskboard
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
