name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'devops/starter/**'
      - 'scripts/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'devops/starter/**'
      - 'scripts/**'

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dockerfile-lint:
    name: Lint Dockerfile (Hadolint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run hadolint on API Dockerfile
        run: |
          docker run --rm -i hadolint/hadolint < devops/starter/api/Dockerfile

  npm-test:
    name: Tests Node (Jest)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: devops/starter/api
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: devops/starter/api/package-lock.json
      - name: Install deps
        run: npm ci
      - name: Run tests
        run: npm test -- --ci

  vuln-scan:
    name: Vulnerability scan (Trivy FS - non-bloquant)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Trivy filesystem scan (HIGH/CRITICAL, non-bloquant)
        continue-on-error: true
        run: |
          docker run --rm -v $PWD:/src -w /src aquasec/trivy:latest fs \
            --no-progress \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            .

  deploy-local:
    name: Execute scripts/deploy_local.sh (simulate local deploy)
    runs-on: ubuntu-latest
    needs: [ npm-test, dockerfile-lint ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy local (script)
        run: bash scripts/deploy_local.sh
      - name: Tear down
        if: always()
        run: docker compose -f devops/starter/docker-compose.yml down -v